name = "Funky Server Season 1"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14045215b0356ecd5c7d26e74930bc4ea033db616dcd5dc9df348b5b0931fc33"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
