name = "Funky Server Season 1"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2e977b019ef2365d301b3eb4cd111e1dd168a138c922335b081dbebf979159f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
