name = "Funky Server Season 1"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db3c716f3b598314777e720a999a51ade32c9bfeeadb3f2f7789b516c92ccc68"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
