name = "Funky Server Season 1"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fc8faaa35d5ddee9daeee7bf12f240f39346b64382fac69424b3d5f9f1d9d06"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
